#!/usr/bin/env bash
# One-shot Cloudflare self-host setup for OpenSEO (generated by Claude).
# Creates KV/D1/R2 resources in YOUR account, patches wrangler.jsonc,
# installs deps, runs D1 migrations, builds, and deploys.
set -euo pipefail

: "${CLOUDFLARE_API_TOKEN:?Set CLOUDFLARE_API_TOKEN before running}"
: "${CLOUDFLARE_ACCOUNT_ID:?Set CLOUDFLARE_ACCOUNT_ID before running}"

API="https://api.cloudflare.com/client/v4"
ACCT="$API/accounts/$CLOUDFLARE_ACCOUNT_ID"
SUFFIX="${SUFFIX:-mlava}"
KV_TITLE="open-seo-$SUFFIX"
OAUTH_TITLE="open-seo-oauth-$SUFFIX"
D1_NAME="open-seo-$SUFFIX"
R2_NAME="open-seo-$SUFFIX"

cf() { # method url [json-data]
  local method="$1" url="$2" data="${3:-}"
  if [ -n "$data" ]; then
    curl -sS -X "$method" "$url" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" -H "Content-Type: application/json" -d "$data"
  else
    curl -sS -X "$method" "$url" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"
  fi
}

echo "==> Verifying API token"
cf GET "$API/user/tokens/verify" | python3 -c 'import sys,json;d=json.load(sys.stdin);assert d.get("success"),d;print("    token OK:",d["result"]["status"])'

kv_create_or_get() {
  local title="$1" id
  id=$(cf POST "$ACCT/storage/kv/namespaces" "{\"title\":\"$title\"}" | python3 -c 'import sys,json;d=json.load(sys.stdin);print(d["result"]["id"] if d.get("success") else "")')
  if [ -z "$id" ]; then
    id=$(cf GET "$ACCT/storage/kv/namespaces?per_page=100" | TITLE="$title" python3 -c 'import sys,json,os;d=json.load(sys.stdin);print(next((n["id"] for n in d["result"] if n["title"]==os.environ["TITLE"]),""))')
  fi
  if [ -z "$id" ]; then echo "FAILED to create/find KV namespace: $title" >&2; exit 1; fi
  echo "$id"
}

echo "==> KV namespace for KV binding: $KV_TITLE"
KV_ID=$(kv_create_or_get "$KV_TITLE");    echo "    id: $KV_ID"
echo "==> KV namespace for OAUTH_KV binding: $OAUTH_TITLE"
OAUTH_ID=$(kv_create_or_get "$OAUTH_TITLE"); echo "    id: $OAUTH_ID"

echo "==> D1 database: $D1_NAME"
D1_ID=$(cf POST "$ACCT/d1/database" "{\"name\":\"$D1_NAME\"}" | python3 -c 'import sys,json;d=json.load(sys.stdin);print(d["result"]["uuid"] if d.get("success") else "")')
if [ -z "$D1_ID" ]; then
  D1_ID=$(cf GET "$ACCT/d1/database?name=$D1_NAME&per_page=100" | NAME="$D1_NAME" python3 -c 'import sys,json,os;d=json.load(sys.stdin);print(next((n["uuid"] for n in d["result"] if n["name"]==os.environ["NAME"]),""))')
fi
if [ -z "$D1_ID" ]; then echo "FAILED to create/find D1 database: $D1_NAME" >&2; exit 1; fi
echo "    id: $D1_ID"

echo "==> R2 bucket: $R2_NAME"
cf POST "$ACCT/r2/buckets" "{\"name\":\"$R2_NAME\"}" | python3 -c '
import sys,json
d=json.load(sys.stdin)
ok=d.get("success") or any("already exists" in e.get("message","").lower() or e.get("code")==10004 for e in d.get("errors",[]))
assert ok, "R2 bucket creation failed (is R2 enabled on your account? Dashboard -> R2): %s" % d
print("    bucket ready")'

echo "==> Patching wrangler.jsonc"
KV_ID="$KV_ID" OAUTH_ID="$OAUTH_ID" D1_ID="$D1_ID" D1_NAME="$D1_NAME" R2_NAME="$R2_NAME" python3 <<'PYEOF'
import os
s=open("wrangler.jsonc").read()
rep={
 "4abd52f3f2c549ac83cc2cb4ceec8620": os.environ["KV_ID"],
 "bd1759494309474a9b423b029967b0db": os.environ["OAUTH_ID"],
 "37bee90a-e1aa-404f-b01e-b0d1d479bda1": os.environ["D1_ID"],
 '"database_name": "open-seo"': '"database_name": "%s"' % os.environ["D1_NAME"],
 '"bucket_name": "open-seo"': '"bucket_name": "%s"' % os.environ["R2_NAME"],
}
changed=False
for a,b in rep.items():
    if a in s and a!=b:
        s=s.replace(a,b); changed=True
open("wrangler.jsonc","w").write(s)
print("    wrangler.jsonc "+("updated" if changed else "already up to date"))
PYEOF

cat > cf-resources.json <<JSONEOF
{"kv":"$KV_ID","oauth_kv":"$OAUTH_ID","d1_id":"$D1_ID","d1_name":"$D1_NAME","r2":"$R2_NAME"}
JSONEOF

echo "==> Installing dependencies"
command -v pnpm >/dev/null 2>&1 || corepack enable
pnpm install

echo "==> Deploying (D1 migrations + build + wrangler deploy)"
pnpm run deploy

echo ""
echo "ALL DONE. Next: enable Cloudflare Access + set secrets (see docs/SELF_HOSTING_CLOUDFLARE_MANUAL.md step 6)."
