/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=badseo/wrangler.jsonc --env=production --include-runtime=false badseo/src/worker-env.d.ts` (hash: a86cf968e75c0ed194ddfb87c6855162)
interface __BaseEnv_Env {
  CONSENT_LOG: KVNamespace;
  CONSENT_RATE_LIMITER: RateLimit;
  GA4_MEASUREMENT_ID: "G-7MXV9FH7SS";
  GA4_ADMIN_VERIFIED: "false";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
